interval: 2
rules:
- destination: Images/
  extensions:
  - .jpg
  - .jpeg
  - .png
  - .gif
  - .bmp
  - .webp
  - .ico
  - .svg
  keywords: []
  name: Images
  sub: true
- destination: Installers/
  extensions:
  - .msi
  - .exe
  keywords: []
  name: Installers
  sub: true
- destination: Archives/
  extensions:
  - .zip
  - .rar
  - .7z
  - .gz
  keywords: []
  name: Archives
  sub: true
- destination: Documents
  extensions:
  - .pdf
  - .docx
  - .txt
  keywords: []
  name: Documents
  sub: true
