rules:
- destination: imgs/
  extensions:
  - .jpg
  - .jpeg
  - .png
  - .gif
  - .bmp
  - .webp
  - .ico
  - .svg
  keywords: []
  name: Images
  sub: true
- destination: docs/
  extensions:
  - .pdf
  - .docx
  - .doc
  - .xlsx
  - .xls
  - .pptx
  - .ppt
  - .txt
  keywords: []
  name: Documents
  sub: true
- destination: D:\Documents\D&D\Tokens
  extensions:
  - .png
  keywords:
  - token
  name: Archives
  sub: true
